spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 7766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
